# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 084239173aecc3490796e507d106e4b61a849c095532739e2a9d5a4decc78cad88fa633176e6f9f6a2750cb3706834df46b34d3d0a8874bb582924a7f8035d79

test:
  secret_key_base: db186af8844543bc5a22e2cf55e93888e42d1aae5f6e412daf82a8173f413d29484ffc5a5d13d716ebb50f6748f643620957cc4ff67f58326e096d269f357f80

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
